### ISSUE TITLE
example demo output for <textarea> page overflows parent

### ISSUE THREAD

**Issue by tannerdolby** [mdn/interactive-examples#1852]
The `<textarea>` inside the demo output overflows at a little bit under Laptop L viewport width (1340px) on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

<img width="930" alt="Screen Shot 2021-06-20 at 10 03 33 AM" src="https://user-images.githubusercontent.com/48612525/122682528-cedc7080-d1ae-11eb-9da8-24e3492e1782.png">

If we add `max-width: 100%` or `width: 100%` like: 

```css
textarea {
    padding: 10px;
    max-width: 100%;
    line-height: 1.5;
    border-radius: 5px;
    border: 1px solid #ccc;
    box-shadow: 1px 1px 1px #999;
}
```

Now, at the same viewport width as the picture above (1340px), the `<textarea>` no longer overflows and looks good on all screen sizes. It will occupy 100% of the space created from `<textarea rows="5" cols="33" ..>`, where `cols` increasing/decreasing will vary the overall width of the `<textarea>`.

<img width="949" alt="Screen Shot 2021-06-20 at 10 15 29 AM" src="https://user-images.githubusercontent.com/48612525/122682826-8c1b9800-d1b0-11eb-83c7-565f44be41b2.png">
