### ISSUE TITLE
Inaccessible color contrast ratio in menu element example

### ISSUE THREAD

**Issue by yashrajbharti** [mdn/interactive-examples#2839]
### What information was incorrect, unhelpful, or incomplete?

The current color scheme of the [menu element example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu#try_it) does not meet accessible contrast standards, making it difficult to read.

### Safari
(EDIT: as mentioned by @estelle, `color: buttontext;` causes the color of button almost the same as its background resulting in a poor color contrast ratio of **1.2**)

![Screenshot 2024-09-16 at 11 11 48 AM](https://github.com/user-attachments/assets/fbe16afc-0d96-4bce-a8f9-fc8a69c47ad1)
### Chrome
![Screenshot 2024-09-16 at 11 12 12 AM](https://github.com/user-attachments/assets/a149b0cf-d790-4ba9-b498-e6f8865b9815)
### Firefox
![Screenshot 2024-09-16 at 11 12 44 AM](https://github.com/user-attachments/assets/3714f831-df7f-48c1-a515-8bf0ed13bc6b)
## Contrast ratio
![Screenshot 2024-09-16 at 11 13 59 AM](https://github.com/user-attachments/assets/4104b604-5001-4447-9b13-dacacaa17664)

### What did you expect to see?

I expected the example to use colors that meet the Web Content Accessibility Guidelines (WCAG) 2.1, specifically the contrast ratio of at least 4.5:1 for normal text.
  
This can be fixed using `background-color: black` and we can remove the black border (if we want).
This fixes both the color between button text and it's background and anchor (link) text and the background.
   
![Screenshot 2024-09-16 at 11 17 01 AM](https://github.com/user-attachments/assets/76a9eb6d-2451-49fa-b793-0b157e3b107b)
![Screenshot 2024-09-16 at 11 17 37 AM](https://github.com/user-attachments/assets/e0bcdf58-eda2-4770-8943-49687c5ca16d)

### Do you have any supporting links, references, or citations?

You can verify the contrast issue using accessibility testing tools like [Contrast Checker](https://webaim.org/resources/contrastchecker/) or by using browser developer tools to inspect the element's styles.

The [menu element example](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu#try_it) can be found here.

### Do you have anything more you want to share?

The issue is reproducible on macOS Monterey using Safari 17.5, Chrome 128.0.6613.138, and Firefox 130.0. It is not browser-specific, as the contrast issue appears consistently across all of them.

**Comment by estelle** [comment]
This actually seems to be an issue with the Safari user agent style sheet setting the color `buttontext`.

Got to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button using Safari. If you remove all the CSS in the live example, the button is not legible.

```css
input:is([type="button"], [type="submit"], [type="reset"]), input[type="file"]::file-selector-button, button {
align-items: flex-start;
text-align: center;
cursor: default;
color: buttontext;
padding-top: 2px;
padding-right: 6px;
padding-bottom: 3px;
padding-left: 6px;
border-top-width: 2px;
border-right-width: 2px;
border-bottom-width: 2px;
border-left-width: 2px;
border-top-style: outset;
border-right-style: outset;
border-bottom-style: outset;
border-left-style: outset;
border-top-color: buttonface;
border-right-color: buttonface;
border-bottom-color: buttonface;
border-left-color: buttonface;
background-color: buttonface;
box-sizing: border-box;
}
```
This is from my Safari's User Agent Style Sheet - the `color: buttontext;` is the culprit. The color `buttontext` in Safari seems to  be `#dcdcdc`.
